-- MySQL Script generated by MySQL Workbench
-- 03/01/16 19:52:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CEP_R_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CEP_R_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CEP_R_v1` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `CEP_R_v1` ;

-- -----------------------------------------------------
-- Table `CEP_R_v1`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`producto` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT(8) NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `imagen` BLOB NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`propiedad` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`propiedad` (
  `idpropiedad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idpropiedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`unidad_medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`unidad_medida` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`unidad_medida` (
  `idunidad_medida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `simbolo` VARCHAR(5) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idunidad_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`propiedad_unidad_medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`propiedad_unidad_medida` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`propiedad_unidad_medida` (
  `idpropiedad` INT NOT NULL,
  `idunidad_medida` INT NOT NULL,
  PRIMARY KEY (`idpropiedad`, `idunidad_medida`),
  CONSTRAINT `fk_Propiedad_has_UnidadMedida_Propiedad1`
    FOREIGN KEY (`idpropiedad`)
    REFERENCES `CEP_R_v1`.`propiedad` (`idpropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propiedad_has_UnidadMedida_UnidadMedida1`
    FOREIGN KEY (`idunidad_medida`)
    REFERENCES `CEP_R_v1`.`unidad_medida` (`idunidad_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Propiedad_has_UnidadMedida_UnidadMedida1_idx` ON `CEP_R_v1`.`propiedad_unidad_medida` (`idunidad_medida` ASC);

CREATE INDEX `fk_Propiedad_has_UnidadMedida_Propiedad1_idx` ON `CEP_R_v1`.`propiedad_unidad_medida` (`idpropiedad` ASC);


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`producto_propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`producto_propiedad` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`producto_propiedad` (
  `idproducto` INT NOT NULL,
  `idpropiedad` INT NOT NULL,
  PRIMARY KEY (`idproducto`, `idpropiedad`),
  CONSTRAINT `fk_Producto_has_Propiedad_Producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `CEP_R_v1`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Propiedad_Propiedad1`
    FOREIGN KEY (`idpropiedad`)
    REFERENCES `CEP_R_v1`.`propiedad` (`idpropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Producto_has_Propiedad_Propiedad1_idx` ON `CEP_R_v1`.`producto_propiedad` (`idpropiedad` ASC);

CREATE INDEX `fk_Producto_has_Propiedad_Producto1_idx` ON `CEP_R_v1`.`producto_propiedad` (`idproducto` ASC);


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`tipo_carta_control`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`tipo_carta_control` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`tipo_carta_control` (
  `idtipo_carta_control` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `simbolo` CHAR NOT NULL,
  `campo_aplicacion` VARCHAR(25) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_carta_control`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`estadistico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`estadistico` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`estadistico` (
  `idestadistico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `simbolo` CHAR NOT NULL,
  `formula` VARCHAR(45) NULL,
  PRIMARY KEY (`idestadistico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`persona` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`persona` (
  `idpersona` INT(8) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`perfil` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`perfil` (
  `idperfil` INT(8) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`usuario` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`usuario` (
  `idusuario` INT(8) NOT NULL AUTO_INCREMENT,
  `perfil_idperfil` INT(8) NOT NULL,
  `persona_idpersona` INT(8) NOT NULL,
  `nombre` VARCHAR(15) NULL,
  `contraseña` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`, `perfil_idperfil`, `persona_idpersona`),
  CONSTRAINT `fk_Usuario_Empleado1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `CEP_R_v1`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `CEP_R_v1`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Persona1_idx` ON `CEP_R_v1`.`usuario` (`persona_idpersona` ASC);

CREATE INDEX `fk_Usuario_Perfil1_idx` ON `CEP_R_v1`.`usuario` (`perfil_idperfil` ASC);


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`permiso` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`permiso` (
  `idpermiso` INT(6) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`perfil_permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`perfil_permiso` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`perfil_permiso` (
  `idperfil` INT(8) NOT NULL,
  `idpermiso` INT(6) NOT NULL,
  PRIMARY KEY (`idperfil`, `idpermiso`),
  CONSTRAINT `fk_Grupo_has_Permiso_Grupo1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `CEP_R_v1`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Permiso_Permiso1`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `CEP_R_v1`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Perfil_has_Permiso_Permiso1_idx` ON `CEP_R_v1`.`perfil_permiso` (`idpermiso` ASC);

CREATE INDEX `fk_Perfil_has_Permiso_Perfil1_idx` ON `CEP_R_v1`.`perfil_permiso` (`idperfil` ASC);


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`tipo_carta_control_estadistico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`tipo_carta_control_estadistico` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`tipo_carta_control_estadistico` (
  `idtipo_carta_control` INT NOT NULL,
  `idestadistico` INT NOT NULL,
  PRIMARY KEY (`idtipo_carta_control`, `idestadistico`),
  CONSTRAINT `fk_TipoCartaControl_has_Estadistico_TipoCartaControl1`
    FOREIGN KEY (`idtipo_carta_control`)
    REFERENCES `CEP_R_v1`.`tipo_carta_control` (`idtipo_carta_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoCartaControl_has_Estadistico_Estadistico1`
    FOREIGN KEY (`idestadistico`)
    REFERENCES `CEP_R_v1`.`estadistico` (`idestadistico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TipoCartaControl_has_Estadistico_Estadistico1_idx` ON `CEP_R_v1`.`tipo_carta_control_estadistico` (`idestadistico` ASC);

CREATE INDEX `fk_TipoCartaControl_has_Estadistico_TipoCartaControl1_idx` ON `CEP_R_v1`.`tipo_carta_control_estadistico` (`idtipo_carta_control` ASC);


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`produccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`produccion` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`produccion` (
  `idproduccion` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT(10) NOT NULL,
  `nombre` VARCHAR(15) NULL,
  `fecha` DATE NOT NULL,
  `turno` TIME NULL,
  `proceso` VARCHAR(15) NULL,
  `operacion` VARCHAR(25) NULL,
  `maquina` VARCHAR(15) NULL,
  `operador` VARCHAR(15) NULL,
  `observacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`lote` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`lote` (
  `idlote` INT NOT NULL AUTO_INCREMENT,
  `produccion_idproduccion` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `codigo` INT(10) NOT NULL,
  `nombre` VARCHAR(15) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idlote`, `produccion_idproduccion`, `producto_idproducto`),
  CONSTRAINT `fk_Lote_Producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `CEP_R_v1`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lote_Produccion1`
    FOREIGN KEY (`produccion_idproduccion`)
    REFERENCES `CEP_R_v1`.`produccion` (`idproduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Lote_Producto1_idx` ON `CEP_R_v1`.`lote` (`producto_idproducto` ASC);

CREATE INDEX `fk_Lote_Produccion1_idx` ON `CEP_R_v1`.`lote` (`produccion_idproduccion` ASC);


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`muestra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`muestra` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`muestra` (
  `idmuestra` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NULL,
  `descripcion` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `producto_idproducto` INT NOT NULL,
  `propiedad_idpropiedad` INT NOT NULL,
  `unidad_medida_idunidad_medida` INT NOT NULL,
  PRIMARY KEY (`idmuestra`, `producto_idproducto`, `propiedad_idpropiedad`, `unidad_medida_idunidad_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`subgrupo_muestra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`subgrupo_muestra` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`subgrupo_muestra` (
  `idsubgrupo_muestra` INT NOT NULL AUTO_INCREMENT,
  `muestra_idmuestra` INT NOT NULL,
  `nombre` INT(2) NOT NULL,
  `valor` DECIMAL NOT NULL,
  `trial` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idsubgrupo_muestra`, `muestra_idmuestra`),
  CONSTRAINT `fk_Subgrupo_Muestra1`
    FOREIGN KEY (`muestra_idmuestra`)
    REFERENCES `CEP_R_v1`.`muestra` (`idmuestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Subgrupo_Muestra1_idx` ON `CEP_R_v1`.`subgrupo_muestra` (`muestra_idmuestra` ASC);


-- -----------------------------------------------------
-- Table `CEP_R_v1`.`grafica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CEP_R_v1`.`grafica` ;

CREATE TABLE IF NOT EXISTS `CEP_R_v1`.`grafica` (
  `idgrafica` INT NOT NULL AUTO_INCREMENT,
  `tipo_carta_control_idtipo_carta_control` INT NOT NULL,
  `muestra_idmuestra` INT NOT NULL,
  `muestra_producto_idproducto` INT NOT NULL,
  `muestra_propiedad_idpropiedad` INT NOT NULL,
  `muestra_unidad_medida_idunidad_medida` INT NOT NULL,
  `imagen` BLOB NOT NULL,
  `media_aritmetica` DECIMAL NULL,
  `amplitud_limite_control` INT NULL,
  `observacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idgrafica`, `tipo_carta_control_idtipo_carta_control`, `muestra_idmuestra`, `muestra_producto_idproducto`, `muestra_propiedad_idpropiedad`, `muestra_unidad_medida_idunidad_medida`),
  CONSTRAINT `fk_Grafica_TipoCartaControl1`
    FOREIGN KEY (`tipo_carta_control_idtipo_carta_control`)
    REFERENCES `CEP_R_v1`.`tipo_carta_control` (`idtipo_carta_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grafica_Muestra1`
    FOREIGN KEY (`muestra_idmuestra`)
    REFERENCES `CEP_R_v1`.`muestra` (`idmuestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Grafica_TipoCartaControl1_idx` ON `CEP_R_v1`.`grafica` (`tipo_carta_control_idtipo_carta_control` ASC);

CREATE INDEX `fk_Grafica_Muestra1_idx` ON `CEP_R_v1`.`grafica` (`muestra_idmuestra` ASC, `muestra_producto_idproducto` ASC, `muestra_propiedad_idpropiedad` ASC, `muestra_unidad_medida_idunidad_medida` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
